#!/usr/bin/env python3
"""
BOUNDED BUILDER · DISC-025 PRIVACY VERSION V1 -> V2
===========================================================================
Founder decision, 8 October 2026.

ONE change to homeowner-facing wording: the "What we keep about you and your
garden" paragraph now explicitly discloses that PlotNua stores the RESULT the
Property Check produced, not only the answers the homeowner supplied. The
stored field `inherited_result_key` is KEPT; the notice is amended to disclose
it. Nothing else about the register changes.

The privacy version therefore advances to 2026-10-PHASE2-V2.

WHY THIS BUILDER EXISTS
-----------------------
disc025-borrowed-garden-check.html is generated by build-g3-garden-interest.py,
which self-blocks on re-run ("This builder is not re-runnable over its own
output"). So the generator cannot reapply the corrected text, and a hand edit
of a generated page is exactly the uncontrolled change this project does not
make. This builder applies the substitution to BOTH files and proves it made
only the substitution.

WHAT THIS BUILDER MUST NEVER DO
-------------------------------
Touch the consent sentences. The garden and grower consent strings are HASHED
by the Worker and compared on every submission. A single byte of drift refuses
every real homeowner with 400 refused - consent_text. Guards P4/P5 below assert
both hashes AFTER the write, not before, because an assertion made before a
write proves nothing about the write.

Run:  python3 atlas-tools/build-g3-privacy-v2.py [--check]
      --check  report only, write nothing.
"""

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "disc025-borrowed-garden-check.html"
GEN = ROOT / "atlas-tools" / "build-g3-garden-interest.py"

CHECK_ONLY = "--check" in sys.argv

# --------------------------------------------------------------- the change --

# The two lines that change, with the page's own indentation and entity
# conventions. The surrounding four lines of the paragraph are NOT in these
# strings and therefore cannot be disturbed.
OLD_NOTICE = (
    "              someone would get in, and whether you own the property. We also keep\n"
    "              the administrative records needed to manage your registration, your\n"
)
NEW_NOTICE = (
    "              someone would get in, and whether you own the property &mdash; and the\n"
    "              result the Property Check produced from those answers. We also keep\n"
    "              the administrative records needed to manage your registration, your\n"
)

OLD_VER = "   * own constant for privacy_version 2026-10-PHASE2-V1. If this page ever\n"
NEW_VER = "   * own constant for privacy_version 2026-10-PHASE2-V2. If this page ever\n"

# ------------------------------------------------------- invariant contract --

# Byte-for-byte, these must survive. Not "approximately" - the first is hashed.
CONSENT_GARDEN = ("I'm over 18, and I'd like PlotNua to keep this and tell me "
                  "if someone nearby is looking for growing space.")
CONSENT_GROWER = ("I'm over 18, and I'd like PlotNua to keep this and tell me "
                  "about possible growing space nearby.")
SHA_GARDEN = "85c436084349e841017171ef12e2c0d5e28fa24a82d99f4c2beaca8f6eee9b9c"
SHA_GROWER = "32ba8b3ec621ed6e15edf0cc4c4fe95bec7b386d9c95179737fe9179990148f1"

# The other four notice paragraphs. Opening fragments are enough to pin them:
# if any were reflowed or reworded these would stop matching.
OTHER_PARAGRAPHS = [
    "<p><strong>What we never ask for.</strong> Your address, your Eircode,",
    "<p><strong>Why we keep it.</strong> So that we can tell you if someone",
    "<p><strong>Joining the register does not share your details with",
    "<p><strong>If we think there&rsquo;s a possible fit, we&rsquo;ll email you",
    "<p><strong>Nothing is shared until you say yes.</strong> Your email",
    "<p><strong>We never sell your information</strong>, and we never pass it",
    "<p><strong>Leaving.</strong> Email hello@plotnua.ie and we will delete",
    "<p><strong>How long we keep it.</strong> We keep your record for a maximum",
    "<p><strong>One thing we keep after deletion.</strong> When we delete your",
]

SWITCHES = [
    ("INTEREST_PUBLIC", "var INTEREST_PUBLIC = false;"),
]

DELTA = len(NEW_NOTICE.encode()) - len(OLD_NOTICE.encode())

fails = []


def gate(name, ok, detail=""):
    print("    %-4s %-58s %s" % ("PASS" if ok else "FAIL", name, detail))
    if not ok:
        fails.append(name)
    return ok


def die(msg):
    print("\n  ABORT: %s" % msg)
    print("  Nothing was written.")
    sys.exit(1)


def sha(b):
    return hashlib.sha256(b if isinstance(b, bytes) else b.encode("utf-8")).hexdigest()


def apply_to(path, label):
    print("\n  %s  %s" % (label, path.name))
    src = path.read_text(encoding="utf-8")
    before = src
    before_sha = sha(src)
    print("    BEFORE  %d bytes  sha256 %s" % (len(src.encode()), before_sha[:16]))

    # ---- P0 idempotence, TESTED FIRST --------------------------------------
    #
    # This check runs ahead of P1 deliberately. After a successful run the old
    # lines are gone, so P1 would find 0 occurrences and abort - reporting a
    # broken file when the file is simply already correct. The guard-capability
    # proof caught exactly that: mutation M3 (a second run) aborted instead of
    # exiting cleanly. Order matters, and "already done" is not a failure.
    if OLD_NOTICE not in src and NEW_NOTICE in src:
        gate("P0 already at V2 - idempotent exit", True,
             "no write needed")
        return "unchanged"

    # ---- P1 the splice point is unique ------------------------------------
    n = src.count(OLD_NOTICE)
    if not gate("P1 old notice lines occur exactly once", n == 1, "found %d" % n):
        die("ambiguous or absent splice point in %s" % path.name)

    # ---- P2 not already half-applied --------------------------------------
    # Both present at once means a previous run was interrupted mid-file, which
    # is the one state that must never be written over silently.
    n2 = src.count(NEW_NOTICE)
    if not gate("P2 new notice lines absent before write", n2 == 0, "found %d" % n2):
        die("%s holds BOTH the old and the new wording - a previous run was "
            "interrupted. Resolve by hand before re-running." % path.name)

    # ---- P3 the version comment is unique ---------------------------------
    nv = src.count(OLD_VER)
    if not gate("P3 V1 version comment occurs exactly once", nv == 1, "found %d" % nv):
        die("ambiguous or absent version comment in %s" % path.name)

    # ---- the substitution -------------------------------------------------
    out = src.replace(OLD_NOTICE, NEW_NOTICE).replace(OLD_VER, NEW_VER)

    # ---- P4/P5 consent bytes and hashes survive, checked on the OUTPUT ----
    gate("P4 garden consent present exactly once after write",
         out.count(CONSENT_GARDEN) == 1, "found %d" % out.count(CONSENT_GARDEN))
    gate("P4b garden consent sha256 unchanged", sha(CONSENT_GARDEN) == SHA_GARDEN,
         sha(CONSENT_GARDEN)[:16])
    if label == "GENERATOR":
        # The grower sentence lives in the Worker, not in the garden page.
        gate("P5 grower consent sha256 unchanged (constant)",
             sha(CONSENT_GROWER) == SHA_GROWER, sha(CONSENT_GROWER)[:16])
    gate("P4c no typographic apostrophe entered the consent sentence",
         "’" not in CONSENT_GARDEN)

    # ---- P6 the byte delta is EXACTLY the expected delta -------------------
    actual = len(out.encode()) - len(before.encode())
    gate("P6 byte delta is exactly the expected delta",
         actual == DELTA, "expected %+d, got %+d" % (DELTA, actual))

    # ---- P7 every other notice paragraph is byte-identical ----------------
    missing = [p for p in OTHER_PARAGRAPHS if out.count(p) != before.count(p)
               or out.count(p) == 0]
    gate("P7 all %d other notice paragraphs unchanged" % len(OTHER_PARAGRAPHS),
         not missing, ", ".join(missing[:2]))

    # ---- P8 switches still closed -----------------------------------------
    if label == "PAGE":
        for nm, needle in SWITCHES:
            gate("P8 %s still false" % nm, out.count(needle) == 1)

    # ---- P6b nothing outside the three edited line-pairs moved ------------
    bl, ol = before.splitlines(True), out.splitlines(True)
    gate("P6b line count grew by exactly 1",
         len(ol) - len(bl) == 1, "%d -> %d" % (len(bl), len(ol)))

    # ---- P3b the new version string is present, old one gone --------------
    gate("P3b V2 comment present, V1 comment gone",
         out.count(NEW_VER) == 1 and out.count(OLD_VER) == 0)

    if fails:
        die("one or more guards failed for %s" % path.name)

    if CHECK_ONLY:
        print("    --check: would write %d bytes (%+d)" % (len(out.encode()), actual))
        return None

    path.write_text(out, encoding="utf-8")
    after_sha = sha(out)
    print("    AFTER   %d bytes  sha256 %s" % (len(out.encode()), after_sha[:16]))
    return after_sha


def main():
    print("\nBOUNDED BUILDER · DISC-025 PRIVACY 2026-10-PHASE2-V1 -> V2")
    print("=" * 72)
    print("  expected byte delta per file: %+d" % DELTA)

    for p in (PAGE, GEN):
        if not p.exists():
            die("missing target: %s" % p)

    # Generator first: if the generator cannot take the change, the page must
    # not take it either, or the two drift silently.
    g = apply_to(GEN, "GENERATOR")
    p = apply_to(PAGE, "PAGE")

    print("\n  RESULT")
    if CHECK_ONLY:
        print("    --check only. Nothing written.")
    else:
        print("    generator sha256 %s" % (g or "unchanged"))
        print("    page      sha256 %s" % (p or "unchanged"))
    print("    guards failed: %d" % len(fails))
    print()
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
