#!/usr/bin/env python3
"""
BOUNDED BUILDER · the Property Check journey exit
===============================================================================
JOB 1 · P0 JOURNEY EXITS.  Founder authorisation, 9 October 2026.

THE HOMEOWNER PROBLEM, measured.  All ten Property Checks are self-contained:
no <footer>, no link to search.html, no link to discoveries.html.  Nine carry a
header with the PlotNua mark linking home plus one link back to their own parent
Discovery; disc026-power-station.html carries no outbound link whatsoever except
your-plot.html and the compute-readiness check.  A homeowner who finishes a
check can save, or go back to one story.  Nothing else.  The twelve other
Discoveries, Search and ordinary site navigation are unreachable from the page
they are standing on.

THE BOUNDARY, stated exactly.  Every check has the shape

    ... <main class="XX-wrap"> THE GOVERNED DECISION EXPERIENCE </main> <script> ENGINE ...

and exactly one "</main>".  This builder splices ONE canonical region
IMMEDIATELY AFTER that "</main>".  Nothing inside <main> is read for meaning,
rewritten, reflowed or moved, and nothing after the region is touched either.
The founder ruling of 9 October 2026 permits exactly this: global site chrome
OUTSIDE a governed Property Check decision experience.

For DISC-025 specifically the V2 homeowner experience stays frozen.  Guard E6
proves the <main> element is byte-identical before and after on all ten pages,
which is the whole of the frozen V2 check / result / interest experience.

WHAT IS DELIBERATELY NOT DONE
  * no question, option, engine, result, evidence, consent, privacy, interest,
    register, payload or switch is read or written
  * no existing call to action is removed, reworded, demoted or restyled — guard
    E9 asserts every pre-existing outbound anchor is still present
  * no <head> is touched, so no inline <style> or <script> in <head> moves
  * no script of any kind is added; the region is markup and scoped CSS only
  * no external asset is added — guard E8.  In particular search.css / search.js
    and the .pns- Search pill are NOT brought onto journey pages: the rail
    builder's own R6 deliberately excludes them, and overriding that is a
    separate founder decision, not this job
  * no skip link, no landmark repair elsewhere, no analytics event, no
    performance work: those are Jobs 2 and 3 and are not authorised

WHY A STUB AND NOT HAND EDITS.  The ten checks share no stylesheet; each is
fully self-contained inline CSS.  "A site-level footer on the checks" therefore
means touching ten governed pages, and hand-editing ten governed pages is
exactly what the bounded-builder convention exists to prevent.  One canonical
region is inserted at one anchor on each page and the builder proves the region
is byte-identical everywhere and that every byte outside it is unchanged.

CSS SCOPE.  The region defines only selectors beginning ".pnx" (guard E11).
"pnx-" appears nowhere else in the repository.  The eleven brand custom
properties the region uses (--paper --ink --soft --accent --line) are defined
IDENTICALLY in all ten checks' :root, measured not assumed (guard E0d), and both
brand typefaces are already loaded on all ten.

    python3 build-journey-exit.py            inject
    python3 build-journey-exit.py --check     guards only, write nothing
    python3 build-journey-exit.py --revert    restore from the recorded baseline
"""

import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATE = ROOT / "atlas-tools" / "journey-exit-baseline.json"

CHECK = "--check" in sys.argv
REVERT = "--revert" in sys.argv

BEGIN = "<!-- PLOTNUA JOURNEY EXIT v1 · BEGIN · generated by " \
        "atlas-tools/build-journey-exit.py — do not hand-edit -->"
END = "<!-- PLOTNUA JOURNEY EXIT v1 · END -->"

# The ten Property Checks. Enumerated explicitly rather than globbed, so the
# scope of this builder can never drift silently when a file is added.
CHECKS = [
    "disc005-home-exchange.html",
    "disc014-driveway-income.html",
    "disc022-hidden-cars-check.html",
    "disc023-buy-original-irish-art.html",
    "disc024-open-your-home-to-art.html",
    "disc025-borrowed-garden-check.html",
    "disc026-compute-readiness-check.html",
    "disc026-power-station.html",
    "disc027-neighbourhood-parcel-house.html",
    "disc029-hidden-bins-check.html",
]

# Brand tokens the region relies on. E0d proves each is defined, and defined
# identically, in every check's :root.
NEEDED_TOKENS = ["--paper", "--ink", "--soft", "--accent", "--line"]

# Baseline file hashes as frozen before this job. E0e refuses to run against
# anything else, so this builder cannot be pointed at an unexpected page state.
EXPECTED_BEFORE = {
    "disc005-home-exchange.html": "d56058696f50",
    "disc014-driveway-income.html": "e850cbfc77f4",
    "disc022-hidden-cars-check.html": "90dcca2a06e6",
    "disc023-buy-original-irish-art.html": "f86b30b71ec4",
    "disc024-open-your-home-to-art.html": "ba3ab4f8ca95",
    "disc025-borrowed-garden-check.html": "df54fd5e3405",
    "disc026-compute-readiness-check.html": "bf36de261ec2",
    "disc026-power-station.html": "ebc0eddc7bbc",
    "disc027-neighbourhood-parcel-house.html": "d2c3ead7b0bf",
    "disc029-hidden-bins-check.html": "e9c857555f7c",
}


def die(msg):
    print("\nREFUSED: " + msg)
    sys.exit(1)


def sha(b):
    return hashlib.sha256(b if isinstance(b, bytes) else b.encode("utf-8")).hexdigest()


# --------------------------------------------------------------- THE ONE REGION
#
# COPY DISCIPLINE.  Three onward routes and ordinary site navigation.  No count
# of Discoveries is printed, because a number in site chrome goes stale the day
# a Discovery is published.  No demand claim, no "people are looking", no
# encouragement to register — this is navigation, and PlotNua's register is
# closed.  "My Plot" is described as what it is: what the homeowner saved, kept
# on their own device.
#
# The heading is a real <h2> so the region is a navigable landmark rather than
# styled text, and the whole thing is a <footer> containing one <nav>, which is
# what it is.

REGION_CSS = """
/* PLOTNUA JOURNEY EXIT v1 — scoped CSS. Every selector begins .pnx so this
   region cannot reach into any journey's own prefixed stylesheet (hx- dw- hc-
   ar- ho- bg- rc- ps- pa- hb- pc- int-). Uses only the five brand custom
   properties proven present and identical in all ten checks. No animation, so
   nothing to gate behind prefers-reduced-motion. */
.pnx{ background:var(--paper); border-top:1px solid var(--line);
      font-family:'Work Sans',system-ui,sans-serif; color:var(--ink); }
.pnx-in{ max-width:1080px; margin:0 auto; padding:54px 24px 40px; }
.pnx-h{ font-family:'Fraunces',Georgia,serif; font-weight:600;
        font-size:clamp(20px,2.2vw,25px); letter-spacing:-.01em; margin:0; }
.pnx-lede{ margin:8px 0 0; max-width:54ch; font-size:15.5px; line-height:1.7;
           color:var(--soft); }
.pnx-routes{ list-style:none; margin:30px 0 0; padding:0; display:grid;
             grid-template-columns:repeat(3,minmax(0,1fr)); gap:26px; }
.pnx-routes > li{ border-top:1px solid var(--line); padding-top:16px; }
.pnx-go{ font-size:16px; font-weight:500; letter-spacing:.01em;
         color:var(--accent); text-decoration:none;
         border-bottom:1px solid rgba(79,107,74,.38); padding-bottom:2px; }
.pnx-go:hover{ border-bottom-color:var(--accent); }
.pnx-go:focus-visible{ outline:2px solid var(--accent); outline-offset:3px; }
.pnx-say{ display:block; margin-top:9px; font-size:14px; line-height:1.65;
          color:var(--soft); }
.pnx-nav{ margin-top:38px; padding-top:20px; border-top:1px solid var(--line);
          display:flex; flex-wrap:wrap; gap:10px 26px; }
.pnx-nav a{ font-size:14px; color:var(--soft); text-decoration:none; }
.pnx-nav a:hover{ color:var(--accent); }
.pnx-nav a:focus-visible{ outline:2px solid var(--accent); outline-offset:3px; }
.pnx-base{ margin:22px 0 0; font-size:13px; color:var(--soft); }
.pnx-base a{ color:var(--soft); }
@media(max-width:760px){
  .pnx-routes{ grid-template-columns:1fr; gap:0; }
  .pnx-routes > li{ padding:16px 0; }
  .pnx-in{ padding:40px 20px 32px; }
}
""".strip("\n")

REGION_HTML = """
<footer class="pnx">
  <div class="pnx-in">
    <h2 class="pnx-h">More from PlotNua</h2>
    <p class="pnx-lede">This check looked at one idea. There are others, and
      they are not all about the same part of a property.</p>
    <ul class="pnx-routes">
      <li>
        <a class="pnx-go" href="discoveries.html">Explore the Discovery Library</a>
        <span class="pnx-say">Every Discovery PlotNua has published, in one place.</span>
      </li>
      <li>
        <a class="pnx-go" href="search.html">Search PlotNua</a>
        <span class="pnx-say">Look for an idea, a product or a supplier by name.</span>
      </li>
      <li>
        <a class="pnx-go" href="your-plot.html">My Plot</a>
        <span class="pnx-say">What you have saved, kept on your own device.</span>
      </li>
    </ul>
    <nav class="pnx-nav" aria-label="PlotNua">
      <a href="index.html">Home</a>
      <a href="about.html">About</a>
      <a href="contact.html">Contact</a>
      <a href="privacy.html">Privacy</a>
      <a href="terms.html">Terms</a>
    </nav>
    <p class="pnx-base">&copy; PlotNua &middot;
      <a href="mailto:hello@plotnua.ie">hello@plotnua.ie</a></p>
  </div>
</footer>
""".strip("\n")

REGION = BEGIN + "\n<style>\n" + REGION_CSS + "\n</style>\n" + REGION_HTML + "\n" + END


def strip_region(text):
    # The leading \n* matters. The splice is "\n\n" + REGION + "\n", and this
    # pattern removes exactly that, so stripping is newline-symmetric wherever
    # the region sits. Without it, a region spliced at the WRONG offset would
    # leave a stray newline and be reported by the byte guard (E2) instead of
    # the boundary guard (E6b) — the mutation proof caught precisely that
    # misattribution, and this is the fix.
    return re.sub(r"\n*" + re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
                  "", text, flags=re.S)


print("\n  BOUNDED BUILDER · the Property Check journey exit")
print("  target: %d Property Checks\n" % len(CHECKS))

# ------------------------------------------------------------------- baseline
baseline = json.loads(STATE.read_text(encoding="utf-8")) if STATE.exists() \
    else {"pages": {}}

if REVERT:
    n = 0
    for f, rec in baseline.get("pages", {}).items():
        p = ROOT / f
        if not p.exists():
            continue
        restored = strip_region(p.read_text(encoding="utf-8"))
        if sha(restored) != rec["before"]:
            die("cannot revert %s cleanly: stripping the region gives %s, "
                "baseline was %s — the page was hand-edited since injection"
                % (f, sha(restored)[:12], rec["before"][:12]))
        p.write_text(restored, encoding="utf-8")
        n += 1
    print("  reverted %d pages to baseline\n" % n)
    sys.exit(0)

# =================================================================== PRE-FLIGHT
for f in CHECKS:
    p = ROOT / f
    if not p.exists():
        die("E0a %s does not exist" % f)
    t = p.read_text(encoding="utf-8")
    if t.count("</main>") != 1:
        die("E0b %s has %d '</main>' — exactly one is required, because the "
            "anchor must be unambiguous" % (f, t.count("</main>")))
    if not re.search(r"<main\b", t):
        die("E0b %s has no <main> open tag" % f)
print("  E0b every check has exactly one <main> … </main>  OK")

for f in CHECKS:
    t = (ROOT / f).read_text(encoding="utf-8")
    if "pnx-" in strip_region(t) or ".pnx" in strip_region(t):
        die("E0c %s already uses the pnx- prefix outside the region — the "
            "scope guarantee would not hold" % f)
print("  E0c the pnx- prefix is unused outside the region on every check  OK")

tokvals = {}
for f in CHECKS:
    t = (ROOT / f).read_text(encoding="utf-8")
    r = re.search(r":root\s*\{(.*?)\}", t, re.S)
    if not r:
        die("E0d %s has no :root block" % f)
    d = dict(re.findall(r"(--[a-z0-9-]+)\s*:\s*([^;]+);", r.group(1)))
    for tok in NEEDED_TOKENS:
        if tok not in d:
            die("E0d %s does not define %s" % (f, tok))
        tokvals.setdefault(tok, set()).add(d[tok].strip())
for tok, vals in tokvals.items():
    if len(vals) != 1:
        die("E0d %s is not identical across the ten checks: %r" % (tok, vals))
print("  E0d all %d brand tokens the region uses are defined IDENTICALLY\n"
      "      in all ten checks (measured): %s  OK"
      % (len(NEEDED_TOKENS), " ".join("%s=%s" % (k, list(v)[0])
                                      for k, v in sorted(tokvals.items()))))

for f in CHECKS:
    base = strip_region((ROOT / f).read_text(encoding="utf-8"))
    if sha(base)[:12] != EXPECTED_BEFORE[f]:
        die("E0e %s baseline is %s, expected %s — this builder refuses to run "
            "against an unexpected page state" % (f, sha(base)[:12],
                                                  EXPECTED_BEFORE[f]))
print("  E0e every check matches its expected frozen baseline hash  OK")

# ======================================================================= BUILD
results = []
for f in CHECKS:
    p = ROOT / f
    original = p.read_text(encoding="utf-8")
    base = strip_region(original)          # idempotent: re-running replaces
    i = base.index("</main>") + len("</main>")
    out = base[:i] + "\n\n" + REGION + "\n" + base[i:]
    results.append({"file": f, "base": base, "text": out, "after": sha(out)})


# THE GUARDS COMPARE AGAINST THE FILE ON DISK, NOT AGAINST THE BUILDER'S OWN
# INTERMEDIATE. The mutation proof showed why: a builder that corrupts `base`
# before deriving `out` makes a base-versus-out comparison trivially pass, and
# three guards went BLIND against exactly that. Re-reading the page is the only
# comparison a defective builder cannot launder.
def disk(f):
    return strip_region((ROOT / f).read_text(encoding="utf-8"))


for r in results:
    r["before"] = sha(disk(r["file"]))

# ====================================================================== GUARDS
print()

# E1 — one canonical region, byte-identical on all ten
regions = set()
for r in results:
    a = r["text"].index(BEGIN)
    b = r["text"].index(END) + len(END)
    regions.add(sha(r["text"][a:b]))
if len(regions) != 1:
    die("E1 the injected region differs between pages: %r" % regions)
print("  E1  injected region sha256 identical on all ten checks\n"
      "      %s  OK" % list(regions)[0])

# E6b — the region really is OUTSIDE <main>
for r in results:
    if r["text"].index(BEGIN) < r["text"].index("</main>"):
        die("E6b %s: the region landed inside <main>" % r["file"])
print("  E6b the region sits after </main> on every check, never inside  OK")

# E5 — idempotence. Runs before the structural guards so that a double
#      injection is reported as a double injection, not as a style-count
#      anomaly downstream.
for r in results:
    if r["text"].count(BEGIN) != 1 or r["text"].count(END) != 1:
        die("E5 %s does not carry exactly one region" % r["file"])
    again = strip_region(r["text"])
    i = again.index("</main>") + len("</main>")
    if again[:i] + "\n\n" + REGION + "\n" + again[i:] != r["text"]:
        die("E5 %s is not idempotent under re-injection" % r["file"])
print("  E5  exactly one region per page, and re-injection is idempotent  OK")

# E9 — NO EXISTING CALL TO ACTION WEAKENED. Every outbound anchor that existed
#      on disk still exists, with its text unchanged.
HREF_RE = re.compile(r'<a\b[^>]*href="([^"]+)"[^>]*>(.*?)</a>', re.S)
for r in results:
    before = HREF_RE.findall(disk(r["file"]))
    after = HREF_RE.findall(r["text"])
    missing = [x for x in before if x not in after]
    if missing:
        die("E9 %s: a pre-existing anchor was lost or reworded: %r"
            % (r["file"], missing[:3]))
print("  E9  every pre-existing anchor (href AND its text) still present on\n"
      "      all ten — no CTA removed, reworded, demoted or restyled  OK")

# E14 — the before/after journey-exit census, computed not asserted. Runs
#       before E12 so that a destination quietly swapped out is reported as a
#       census failure rather than as a missing literal.
print("\n  E14 JOURNEY-EXIT CENSUS")
print("      %-42s %-10s %s" % ("check", "before", "after"))
WANT = ["discoveries.html", "search.html", "your-plot.html", "index.html"]


def have(t):
    hs = [h for h, _ in HREF_RE.findall(t)]
    return "".join("D" if any(w in h for h in hs) else "." for w in WANT)


for r in results:
    b, a = have(disk(r["file"])), have(r["text"])
    print("      %-42s %-10s %s" % (r["file"], b, a))
    if a != "DDDD":
        die("E14 %s still lacks one of %r after injection" % (r["file"], WANT))
print("      columns: discoveries / search / your-plot / index")
print("      all ten now reach all four  OK\n")

# E12 — accessibility and semantics essentials of the region itself
for need in ('<footer class="pnx">', '<nav class="pnx-nav" aria-label="PlotNua">',
             '<h2 class="pnx-h">', 'href="discoveries.html"',
             'href="search.html"', 'href="your-plot.html"',
             'href="index.html"', 'focus-visible'):
    if need not in REGION:
        die("E12 the region is missing %r" % need)
print("  E12 region is a real <footer> with a labelled <nav>, an <h2>, visible\n"
      "      focus rings, and all four required destinations  OK")

# E4 — editorial prose outside the region byte-identical, against disk. Runs
#      before the raw byte guard so a reworded sentence is reported as a copy
#      change rather than as an anonymous byte difference.
def prose(t):
    t = strip_region(t)
    t = re.sub(r"<script.*?</script>", " ", t, flags=re.S | re.I)
    t = re.sub(r"<style.*?</style>", " ", t, flags=re.S | re.I)
    t = re.sub(r"<!--.*?-->", " ", t, flags=re.S)
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", t)).strip()


for r in results:
    if prose(disk(r["file"])) != prose(r["text"]):
        die("E4 %s: editorial prose changed" % r["file"])
print("  E4  all journey editorial prose outside the region byte-identical  OK")

# E6 — THE FROZEN DECISION EXPERIENCE. <main> … </main> byte-identical,
#      compared against the page on disk. For DISC-025 this element IS the
#      frozen V2 check / result / interest experience, so this is the proof the
#      founder ruling requires.
MAIN_RE = re.compile(r"<main\b.*?</main>", re.S)
for r in results:
    a = MAIN_RE.search(disk(r["file"])).group(0)
    b = MAIN_RE.search(r["text"]).group(0)
    if a != b:
        die("E6 %s: the <main> decision experience changed" % r["file"])
print("  E6  <main> … </main> byte-identical on all ten, against the page on\n"
      "      disk — questions, options, engine, result, evidence, interest\n"
      "      and copy all untouched  OK")

# E3 — every pre-existing inline <style> and <script> body byte-identical
#      against disk. The region adds exactly one <style> body and no <script>.
def bodies(t, tag):
    return [x for x in re.findall(r"<%s(?:\s[^>]*)?>(.*?)</%s>" % (tag, tag),
                                  t, re.S) if x.strip()]


for r in results:
    d = disk(r["file"])
    for tag in ("style", "script"):
        if bodies(d, tag) != bodies(strip_region(r["text"]), tag):
            die("E3 %s: a pre-existing inline <%s> body changed" % (r["file"], tag))
    if len(bodies(r["text"], "style")) != len(bodies(d, "style")) + 1:
        die("E3 %s: the region should add exactly one <style> body" % r["file"])
    if len(bodies(r["text"], "script")) != len(bodies(d, "script")):
        die("E3 %s: the region must add no <script> body" % r["file"])
print("  E3  every pre-existing inline <style>/<script> body byte-identical;\n"
      "      region adds one <style> and zero <script>  OK")

# E2 — the catch-all. EVERY byte outside the injection point unchanged, against
#      the page on disk. Deliberately LAST of the comparison guards: it would
#      otherwise claim every failure the specific guards above describe better.
for r in results:
    if strip_region(r["text"]) != disk(r["file"]):
        die("E2 %s changed outside the injection point" % r["file"])
print("  E2  every byte outside the injection point unchanged (round-trip\n"
      "      against the page on disk)  OK")

# E7 — the region carries no storage, no analytics, no network, no script
for bad in ("localStorage", "sessionStorage", "indexedDB", "dataLayer",
            "gtag(", "fetch(", "XMLHttpRequest", "sendBeacon", "<script",
            "onclick", "javascript:"):
    if bad in REGION:
        die("E7 the region contains %r" % bad)
print("  E7  region carries no script, storage, analytics or network call  OK")

# E8 — the region introduces no external asset, and specifically does not
#      bring the Search pill or its shared assets onto a journey page
for bad in ("search.css", "search.js", "pns-", "<link", "<img", "src=",
            "https://", "http://"):
    if bad in REGION:
        die("E8 the region references the external asset or prefix %r" % bad)
print("  E8  region adds no external asset; search.css / search.js / .pns-\n"
      "      deliberately NOT brought onto journey pages  OK")

# E11 — CSS scope: every selector in the region's <style> begins .pnx
css = REGION[REGION.index("<style>") + 7:REGION.index("</style>")]
css_nc = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
sel_text = re.sub(r"@media[^{]*\{", "", css_nc)
for block in re.finditer(r"([^{}]+)\{", sel_text):
    for sel in block.group(1).split(","):
        sel = sel.strip()
        if not sel:
            continue
        if not sel.startswith(".pnx"):
            die("E11 the region declares the unscoped selector %r — it could "
                "reach into a journey's own stylesheet" % sel)
print("  E11 every selector in the region's CSS begins '.pnx' — no journey\n"
      "      stylesheet can be reached  OK")

# E13 — NO MISLEADING CTA. The region must not make a demand, matching or
#       registration claim, and must not invite registration: the homeowner
#       register is CLOSED and this is navigation, not an offer.
for bad in ("register", "Register", "looking for somewhere", "match", "Match",
            "sign up", "Sign up", "subscribe", "Subscribe", "free", "Free",
            "guarantee", "earn", "income", "worth"):
    if bad in REGION:
        die("E13 the region contains the claim or invitation %r" % bad)
print("  E13 region makes no demand, matching, registration, pricing or\n"
      "      earnings claim, and invites no sign-up  OK")

print("\n  14 guard families passed.")

if CHECK:
    print("  --check: nothing written.\n")
    sys.exit(0)

for r in results:
    (ROOT / r["file"]).write_text(r["text"], encoding="utf-8")
    baseline["pages"][r["file"]] = {"before": r["before"], "after": r["after"]}
baseline["region"] = sha(REGION)
STATE.write_text(json.dumps(baseline, indent=2, sort_keys=True), encoding="utf-8")
print("  WROTE %d pages + the baseline record\n" % len(results))
for r in results:
    print("    %-44s %s -> %s" % (r["file"], r["before"][:12], r["after"][:12]))
print()
