#!/usr/bin/env python3
"""
BOUNDED BUILDER · the global Search rail stub
===============================================================================
Founder decision B-1: the rail is  MARK -> SEARCH -> INFO.
Founder decision B-2: search.js / search.css are PlotNua's first shared local
front-end assets, and that approval is SPECIFIC TO SEARCH.

WHY A STUB AND NOT HAND EDITS. PlotNua has no shared CSS or JS: all 161 pages
are self-contained, inline style and inline script, with zero local external
assets. There is no existing mechanism to hook into, so "global search" means
touching 20 public pages. Hand-editing 20 frozen pages is exactly what the
founder ruled out, so ONE canonical stub is inserted at ONE anchor on each
page, and the builder proves:

  * the injected region's sha256 is IDENTICAL on every page
  * every byte OUTSIDE the injection point is unchanged
  * no page's editorial text, inline <style> or inline <script> moves
  * no Property Check journey page is touched at all

WHAT IS NOT DONE, deliberately: no existing inline CSS or JS is extracted, no
page is refactored, no component system is created, no unrelated page
architecture is altered.

TWO MARK FAMILIES, MEASURED NOT ASSUMED. Most pages carry .brand-mark at 46x46
with opacity:0 until a script adds .in. discoveries.html carries it at 44x44
with NO .in mechanism and no fade. A single CSS fade rule keyed on
.brand-mark.in would therefore leave the search control invisible on
discoveries.html, so the builder reads each page and sets data-pns-nofade where
the page has no .in mechanism. Detected per page, recorded in the report.

    python3 build-search-rail.py            inject
    python3 build-search-rail.py --check    guards only, write nothing
    python3 build-search-rail.py --revert   restore from the recorded baseline
"""

import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITEMAP = ROOT / "sitemap.xml"
STATE = ROOT / "atlas-tools" / "search-rail-baseline.json"

CHECK = "--check" in sys.argv
REVERT = "--revert" in sys.argv

MARK_RE = re.compile(r'(<a[^>]*class="brand-mark"[^>]*>.*?</a>)', re.S)
BEGIN = "<!-- PLOTNUA SEARCH RAIL v1 · BEGIN · generated by "\
        "atlas-tools/build-search-rail.py — do not hand-edit -->"
END = "<!-- PLOTNUA SEARCH RAIL v1 · END -->"


def die(msg):
    print("\nREFUSED: " + msg)
    sys.exit(1)


def sha(b):
    return hashlib.sha256(b if isinstance(b, bytes) else b.encode("utf-8")).hexdigest()


def stub(nofade):
    """THE ONE CANONICAL STUB — a TOP-RIGHT SEARCH PILL.

    FOUNDER REVIEW REJECTED the previous design. It put a small circular
    magnifying-glass control into the left rail as MARK -> SEARCH -> INFO, which
    meant moving the information control and its popover to make room. That is
    reverted in full: the left-hand PlotNua mark and information control are
    back at their original geometry, byte-identical to what shipped, and this
    stub no longer declares a single rule about either of them.

    Instead Search is a labelled pill in the top right:  [icon] Search PlotNua

    THE LABEL IS KEPT AT EVERY WIDTH, including 390px, because the founder asked
    for a proper labelled control and not an unexplained icon. Measured, not
    assumed: at 390px the pill is ~150px against 358px of available width, so
    there is no case for dropping the label."""
    nf = ' data-pns-nofade="true"' if nofade else ''
    return (
        BEGIN + "\n"
        '<link rel="stylesheet" href="search.css">\n'
        '<a class="pns-pill" id="pnsOpen" href="search.html"'
        ' aria-label="Search PlotNua"' + nf + '>\n'
        '  <span class="pns-pill-ico-wrap" aria-hidden="true">\n'
        '    <svg class="pns-pill-ico" viewBox="0 0 16 16" fill="none"'
        ' stroke="currentColor" stroke-width="1.8" stroke-linecap="round">\n'
        '      <circle cx="6.8" cy="6.8" r="4.4"></circle><path d="M10.2 10.2 14 14"></path>\n'
        '    </svg>\n'
        '  </span>\n'
        '  <span class="pns-pill-label">Search PlotNua</span>\n'
        '  <span class="pns-pill-cue" aria-hidden="true"></span>\n'
        '</a>\n'
        '<div class="pns-panel" id="pnsPanel" role="dialog" aria-modal="true"'
        ' aria-label="Search PlotNua" hidden>\n'
        '  <button type="button" class="pns-close" id="pnsClose"'
        ' aria-label="Close search">\u00d7</button>\n'
        '  <div class="pns-shell">\n'
        '    <h2 class="pns-ask">What are you looking for?</h2>\n'
        '    <div class="pns-field">\n'
        '      <input type="search" class="pns-input" id="pnsInput"'
        ' autocomplete="off" autocorrect="off" spellcheck="false"'
        ' enterkeyhint="search"'
        ' placeholder="Search ideas, products and suppliers">\n'
        '    </div>\n'
        '    <p class="pns-note" id="pnsStatus" role="status" aria-live="polite"></p>\n'
        '    <div id="pnsResults"></div>\n'
        '  </div>\n'
        '</div>\n'
        '<script src="search.js" defer></script>\n'
        + END
    )


def strip_stub(text):
    return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "", text, flags=re.S)


# --------------------------------------------------------------- target pages
pages = [p for p in re.findall(r"<loc>https://plotnua\.ie/([^<]*)</loc>",
                               SITEMAP.read_text(encoding="utf-8")) if p.endswith(".html")]
pages = sorted(set(pages + ["index.html"]))
# 21 = the 20 pre-existing public pages (19 sitemap entries + index.html) PLUS
# search.html itself, added to the sitemap by this work. The founder's "global
# navigation completeness" rule requires the rail on search.html too: it must
# not visually disappear when the homeowner reaches Search.
#
# THIS GUARD FIRED when search.html was added, and it was right to. The expected
# count is stated explicitly so the rail scope can never drift silently — if a
# new public page appears, the builder stops and a human decides.
EXPECTED_PAGES = 21
if len(pages) != EXPECTED_PAGES:
    die("expected %d public pages, found %d — refusing to guess the rail scope. "
        "If a public page was added or removed, update EXPECTED_PAGES "
        "deliberately." % (EXPECTED_PAGES, len(pages)))

JOURNEYS = sorted(p.name for p in ROOT.glob("disc0*.html"))
PREVIEWS = sorted(p.name for p in ROOT.glob("*-preview.html"))

print("\n  BOUNDED BUILDER · the global Search rail stub")
print("  target: %d public pages\n" % len(pages))

# ------------------------------------------------------------------- baseline
if STATE.exists():
    baseline = json.loads(STATE.read_text(encoding="utf-8"))
else:
    baseline = {"pages": {}}

if REVERT:
    n = 0
    for f, rec in baseline.get("pages", {}).items():
        p = ROOT / f
        if not p.exists():
            continue
        cur = p.read_text(encoding="utf-8")
        restored = strip_stub(cur)
        if sha(restored) != rec["before"]:
            die("cannot revert %s cleanly: stripping the stub gives %s, baseline "
                "was %s — the page was edited by hand since injection"
                % (f, sha(restored)[:16], rec["before"][:16]))
        p.write_text(restored, encoding="utf-8")
        n += 1
    print("  reverted %d pages to baseline\n" % n)
    sys.exit(0)

# =================================================================== PRE-FLIGHT
for f in pages:
    p = ROOT / f
    if not p.exists():
        die("R0 sitemap lists %s but the file does not exist" % f)
    t = p.read_text(encoding="utf-8")
    if not MARK_RE.search(t):
        die("R0 %s has no .brand-mark anchor — the rail has nowhere to attach, "
            "and guessing an anchor on a frozen page is not acceptable" % f)
    if len(MARK_RE.findall(t)) != 1:
        die("R0 %s has %d .brand-mark anchors; exactly one is required"
            % (f, len(MARK_RE.findall(t))))
print("  R0  every page has exactly one .brand-mark anchor  OK")

for f in ("search.css", "search.js"):
    if not (ROOT / f).exists():
        die("R1 the shared asset %s does not exist" % f)
print("  R1  both shared assets present (search.css, search.js)  OK")

# ======================================================================= BUILD
results = []
for f in pages:
    p = ROOT / f
    original = p.read_text(encoding="utf-8")
    base = strip_stub(original)          # idempotent: re-running replaces
    before_sha = sha(base)
    nofade = ".brand-mark.in" not in base
    s = stub(nofade)
    m = MARK_RE.search(base)
    out = base[:m.end()] + "\n" + s + base[m.end():]
    results.append({
        "file": f, "before": before_sha, "after": sha(out),
        "nofade": nofade, "region": sha(s), "text": out,
        "base": base,
    })

# ====================================================================== GUARDS
print()

# R2 the injected region is identical within each variant
variants = {}
for r in results:
    variants.setdefault(r["nofade"], set()).add(r["region"])
for nofade, hashes in variants.items():
    if len(hashes) != 1:
        die("R2 the injected region differs between pages of the same variant "
            "(nofade=%s): %r" % (nofade, hashes))
print("  R2  injected region sha256 identical within each variant:")
for nofade, hashes in sorted(variants.items()):
    n = sum(1 for r in results if r["nofade"] == nofade)
    print("        nofade=%-5s %d page(s)  %s" % (nofade, n, list(hashes)[0][:16]))

# R3 EVERYTHING OUTSIDE THE INJECTION POINT IS UNCHANGED
for r in results:
    if strip_stub(r["text"]) != r["base"]:
        die("R3 %s changed outside the injection point" % r["file"])
    if sha(strip_stub(r["text"])) != r["before"]:
        die("R3 %s does not round-trip to its baseline sha" % r["file"])
print("  R3  every byte outside the injection point unchanged (round-trip)  OK")

# R4 inline <style> and <script> blocks byte-identical
blk = lambda t, tag: re.findall(r"<%s(?:\s[^>]*)?>(.*?)</%s>" % (tag, tag), t, re.S)
for r in results:
    for tag in ("style", "script"):
        a, b = blk(r["base"], tag), blk(r["text"], tag)
        # the stub adds one external <script src>, which has no body
        a2 = [x for x in a if x.strip()]
        b2 = [x for x in b if x.strip()]
        if a2 != b2:
            die("R4 %s: an inline <%s> body changed" % (r["file"], tag))
print("  R4  every inline <style> and <script> body byte-identical  OK")

# R5 editorial text unchanged: all visible prose outside the stub
def prose(t):
    t = strip_stub(t)
    t = re.sub(r"<script.*?</script>", " ", t, flags=re.S | re.I)
    t = re.sub(r"<style.*?</style>", " ", t, flags=re.S | re.I)
    t = re.sub(r"<!--.*?-->", " ", t, flags=re.S)
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", t)).strip()

for r in results:
    if prose(r["base"]) != prose(r["text"]):
        die("R5 %s: editorial prose changed" % r["file"])
print("  R5  Discovery and page editorial prose byte-identical  OK")

# R6 NO journey page touched
touched = {r["file"] for r in results}
if touched & set(JOURNEYS):
    die("R6 a Property Check journey page is in the rail scope: %r"
        % sorted(touched & set(JOURNEYS)))
print("  R6  no Property Check journey page touched (%d journeys)  OK" % len(JOURNEYS))

# R7 NO preview touched
if touched & set(PREVIEWS):
    die("R7 a private supplier preview is in the rail scope")
print("  R7  no private supplier preview touched (%d previews)  OK" % len(PREVIEWS))

# R8 the stub carries no search term, no storage, no analytics
s_all = stub(True) + stub(False)
for bad in ("localStorage", "sessionStorage", "dataLayer", "gtag(", "?q=",
            "sendBeacon", "indexedDB"):
    if bad in s_all:
        die("R8 the stub contains %r" % bad)
if 'type="search"' not in s_all:
    die("R8 the stub has no search input")
print("  R8  the stub carries no storage, analytics or query-string path  OK")

# R9 accessibility essentials present
for need in ('aria-label="Search PlotNua"', 'role="dialog"',
             'aria-modal="true"', 'aria-live="polite"',
             'href="search.html"'):
    if need not in s_all:
        die("R9 the stub is missing %r" % need)
print("  R9  pill and panel carry the required ARIA, and the pill is a real\n"
      "      <a href=\"search.html\"> so it works with JavaScript disabled  OK")

# R10 idempotence: exactly one stub after injection, and re-running is stable
for r in results:
    if r["text"].count(BEGIN) != 1 or r["text"].count(END) != 1:
        die("R10 %s does not carry exactly one stub" % r["file"])
    again = strip_stub(r["text"])
    m = MARK_RE.search(again)
    twice = again[:m.end()] + "\n" + stub(r["nofade"]) + again[m.end():]
    if twice != r["text"]:
        die("R10 %s is not idempotent under re-injection" % r["file"])
print("  R10 exactly one stub per page, and re-injection is idempotent  OK")

print("\n  10 guards passed.")

if CHECK:
    print("  --check: nothing written.\n")
    sys.exit(0)

for r in results:
    (ROOT / r["file"]).write_text(r["text"], encoding="utf-8")
    baseline["pages"][r["file"]] = {"before": r["before"], "after": r["after"],
                                    "nofade": r["nofade"], "region": r["region"]}
STATE.write_text(json.dumps(baseline, indent=2, sort_keys=True), encoding="utf-8")
print("  WROTE %d pages + the baseline record\n" % len(results))
for r in results:
    print("    %-46s %s -> %s%s" % (r["file"], r["before"][:12], r["after"][:12],
                                    "  (nofade)" if r["nofade"] else ""))
print()
