#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
JOB 5 · SHARED VISUAL ACCESSIBILITY LAYER
===============================================================================
Four proven Job 3 findings and nothing else: D contrast, E reduced motion,
F the infinite My Plot pulse, B carousel-dot hit targets.

WHY ONE APPENDED BLOCK PER PAGE RATHER THAN EDITING THE EXISTING RULES.
The failing declarations are not page-specific: `.footer-base` is one literal
duplicated across 21 pages, `.sub` also exists on index, `.d-tag` also exists
on your-plot, and `.n` exists on fourteen pages. Editing those declarations in
place would silently repaint surfaces this job never measured. So each page
gets ONE clearly marked override block carrying only the rules that page's own
measured failures need. A reader can delete the block and have the page back.

WHY NOT CHANGE THE BRAND TOKENS. --brand-sage #8FAF8A fails on ivory (2.22)
and PASSES on the dark ground (5.03, which is why the footer headings only
needed their opacity removed). Retuning the token would fix one and break the
other, and would reach surfaces outside this job. The overrides are scoped.

THE COLOURS. Each is the minimum move along the SAME hue and saturation that
reaches WCAG AA at the text's real size, computed against the real painted
background, not guessed:

  .footer-col h2   opacity .85 -> 1       4.10 -> 5.03   NO colour change
  .discover .lede  --accent -> --brand-sage  2.05 -> 5.03   existing token
  .footer-base     #7C7565 -> #A39D8E     2.66 -> 4.51
  .d-tag (404)     --oak   -> #B49979     2.60 -> 4.51
  .sub   (404)     #9C9587 -> #A39D90     4.10 -> 4.52
  sage on ivory    #8FAF8A -> #557550     2.22 -> 4.76  (.related-kicker,
                   (.n, on paper)         2.11 -> 4.51   .r-kicker, .step-num)

#557550 clears every ivory/paper ground this job touches (measured 4.76 on
ivory, 4.51 on the slightly darker paper) and stays
well below the ink used for primary copy (11.18), so muted text stays muted.

REDUCED MOTION reuses the homepage's own established treatment verbatim --
    .reveal{ opacity:1 !important; transform:none !important; transition:none !important; }
-- which its author wrote precisely because a 1.1s fade met the visitor five
times per page. The same principle is extended to the surfaces that never got
it, plus the shared brand mark, the 404 hero and the My Plot screens, and the
My Plot status pulse is stopped. Nothing that communicates STATE is removed:
the pulse's element, colour and meaning are untouched, only its endless
animation stops for people who asked for less movement.

CAROUSEL DOTS keep their painted 7px/10px exactly. A transparent ::after gives
each one a 24x24 hit target, and the row gap goes 9px -> 17px so centres sit
24px apart -- without that, 24px targets would overlap and the neighbour would
steal the click. Row width grows about 199px -> 303px, which still fits 390px.

    python3 atlas-tools/build-a11y-visual.py            apply
    python3 atlas-tools/build-a11y-visual.py --check    verify, write nothing
    python3 atlas-tools/build-a11y-visual.py --revert   undo
"""

import hashlib
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BEGIN = "/* PLOTNUA A11Y VISUAL v1 · BEGIN · generated by atlas-tools/build-a11y-visual.py */"
END = "/* PLOTNUA A11Y VISUAL v1 · END */"

DISC025 = "disc025-borrowed-garden-check.html"
DISC025_MAIN_SHA = "05bf977f0d4fb05a3310e1e3dc9bfb757b2d92d529f226f2c8bb97c805844a29"
FROZEN = {
    # Re-stamped by JOB 6, which was authorised to change search.js so the
    # Search modal actually contains focus. The assertion itself is unchanged
    # and still refuses the build if search.js moves again.
    "search.js":  "c7307b28d8629f278c021aaf105d8bd69f1c42db2890c51d9efd1b6acc63bf27",
    "search-index-v1.json": "98efc7e85f796ba818548d254505dca68a7433f03f1b5319962a323cab963d20",
}

DISCOVERIES = [
    "discovery-living-in-the-garden.html", "discovery-a-home-for-art.html",
    "discovery-open-your-home-to-art.html", "discovery-the-borrowed-garden.html",
    "discovery-house-as-power-station.html", "discovery-neighbourhood-parcel-house.html",
    "discovery-hidden-cars.html", "discovery-hidden-bins.html",
    "discovery-garden-retreat.html", "discovery-above-and-beyond.html",
    "discovery-your-home-on-screen.html", "discovery-driveway-income.html",
    "discovery-home-exchange.html",
]
FOOTER_PAGES = ["index.html", "404.html", "about.html", "contact.html",
                "privacy.html", "terms.html", "cookie-policy.html"] + DISCOVERIES

# ---------------------------------------------------------------- fragments
FOOTER_FIX = """
/* D · the shared footer. The column headings needed no new colour at all --
   they are brand sage already, held at opacity .85, which dropped them to
   4.10:1. Full opacity restores the brand colour and clears AA at 5.03:1.
   The (c) line is a warm grey lightened the minimum distance to 4.51:1. */
.footer-col h2{ opacity:1; }
.footer-base{ color:#A39D8E; }"""

LEDE_FIX = """
/* D · the Discovery Library lede sits on the dark ground at 2.05:1 in the
   mid-green accent. Brand sage is an existing PlotNua colour already used on
   this exact ground by the footer headings, and reads 5.03:1. */
.discover .lede{ color:var(--brand-sage); }"""

FOUR_OH_FOUR_FIX = """
/* D · 404 only. The category tag keeps its warm oak character, lightened the
   minimum distance; the sub line moves barely at all (+0.03 lightness). */
.d-tag{ color:#B49979; }
/* Scoped to match the original's own specificity. The declaration this has to
   override is `.discover .sub` (0-2-0); a bare `.sub` (0-1-0) loses the
   cascade however late it appears, which an earlier revision of this builder
   proved by leaving the measured ratio at 4.10 unchanged. */
.discover .sub{ color:#A39D90; }"""

SAGE_ON_LIGHT_FIX = """
/* D · brand sage on the ivory and paper grounds reads 2.11-2.22:1. One value,
   the minimum darkening of that same hue, clears every light ground here
   while staying far lighter than the ink used for primary copy; measured, it
   lands at 4.76 on the ivory ground and higher on the slightly darker paper.
   Each selector mirrors the specificity of the declaration it has to beat and
   wins on source order alone, so no !important is needed and no brand token
   moves. `.step-num` is genuinely unscoped; the other three are not, and the
   flat one-class form left all three measurably unchanged. The `.n` override
   is deliberately scoped to `.pb-step` only: `.atlas-figs .n` and
   `.platform-beats .n` on the homepage are var(--ink), already pass, and must
   not be touched. */
.step-num{ color:#557550; }
.related-card .related-kicker,
.related-card .r-kicker,
.pb-step .n{ color:#557550; }"""

REDUCED_MOTION = """
/* E · reduced motion. This reuses the treatment the homepage already carries,
   whose author noted the 1.1s scroll-reveal "is a 1.1s fade and lift on every
   section ... Content is shown outright instead." The same principle is
   applied to the surfaces that never received it. Content must never depend
   on an animation finishing. */
@media (prefers-reduced-motion: reduce){
  .reveal{ opacity:1 !important; transform:none !important; transition:none !important; }
  .article-section, .imagine-photo, .pb-preview, .related, .closing-line,
  .spark, .seam, .brand-mark, .brand-info{
    transition-duration:.01ms !important; animation-duration:.01ms !important;
    transform:none !important; opacity:1 !important;
  }
  /* The related-card thumbnail zooms on hover over 1s -- movement, so it is
     stilled. The sibling `.thumb` box-shadow transition is deliberately left
     alone: a shadow fade is not motion, and removing it would take away a
     hover affordance for no accessibility gain. */
  .related-card .thumb img{
    transition-duration:.01ms !important; transform:none !important;
  }
  html{ scroll-behavior:auto !important; }
}"""

HERO_404 = """
  .hero-eyebrow, .hero-word, .hero-tagline, .hero-sub, .hero-actions{
    transition-duration:.01ms !important; opacity:1 !important; transform:none !important;
  }"""

MYPLOT_MOTION = """
/* E + F · My Plot. The screens' entrance is suppressed, and the status mark
   stops pulsing. F is a reduced-motion fix ONLY: the mark keeps its element,
   its colour and its meaning, and under normal motion it behaves exactly as
   before. Nothing that communicates state is removed. */
@media (prefers-reduced-motion: reduce){
  .brand-mark, .reveal-card{
    transition-duration:.01ms !important; transform:none !important; opacity:1 !important;
  }
  .screen{ transition-duration:.01ms !important; }
  /* Duration only. These two are the floating status pill and the interaction
     hint: they are shown and hidden by script, so forcing opacity or
     visibility here would pin them permanently on screen. */
  #statusPill, #interactionHint{ transition-duration:.01ms !important; }
  .pn-status-mark{ animation:none !important; }
  .pn-dl-dot{ animation:none !important; }
  html{ scroll-behavior:auto !important; }
}"""

DISCOVERIES_MOTION = """
/* E · the Discovery Library cards lift on hover/entrance. */
@media (prefers-reduced-motion: reduce){
  .d-card img, .img, .lib-shot img{
    transition-duration:.01ms !important; transform:none !important; }
  html{ scroll-behavior:auto !important; }
}"""

DOTS_FIX = """
/* B · carousel position controls. The painted dot is untouched at 7px (10px
   when current). A transparent ::after gives each control a 24x24 hit target,
   and the row gap goes 9px -> 17px so adjacent centres sit 24px apart. Without
   the gap change the enlarged targets would overlap and a neighbour would take
   the click, which would be worse than the small target it replaced. */
.d-dots{ gap:17px; }
button.d-dot{ position:relative; }
button.d-dot::after{
  content:""; position:absolute; left:50%; top:50%;
  width:24px; height:24px; transform:translate(-50%,-50%);
}
/* The page already carries `.d-dot[aria-current="true"]{transform:scale(1.4)}`,
   which scales this pseudo-element along with the dot, so the current control's
   target rendered about 33.6px rather than 24px and, painted last, covered part
   of its neighbour's target -- leaving that neighbour only 19px of its own
   clickable width. Measured, not assumed. Dividing the scale back out here
   makes every target render a uniform 24x24 whatever the current index is. The
   scale rule itself, and the painted dot, are left exactly as they were.
   The box is 25px rather than 24px purely as rounding headroom: 24 x (1/1.4)
   x 1.4 lands on 23.999px in floating point, which hit-tests as 23. */
button.d-dot[aria-current="true"]::after{
  width:25px; height:25px;
  transform:translate(-50%,-50%) scale(calc(1 / 1.4));
}"""


DOTS_404_CLEARANCE = """
/* B (residual) · 404 narrow widths only, authorised by the founder after
   visual acceptance. The last position control sits 9.4px from the right edge
   of `.d-carousel`, which is a pre-existing `overflow:auto` scroller: it clips
   the centred 24px target, leaving that one control 22x26.

   Padding and margin were tried first and measurably do NOTHING here -- the
   row is a flex item in a scroller resting at its maximum scroll offset, so
   extra trailing space just lengthens the scrollable content and the painted
   position never moves. Measured: margin-right 8px and 12px, and
   padding-right 8px on the row's centring parent, all left the control at
   22x26. Only moving the row inward works.

   3px is the smallest value with any margin: 2px lands exactly on 24, 3px
   gives 25x26. The overflow is NOT relaxed or removed -- the scroller keeps
   its clipping behaviour untouched. Nothing else moves: the painted dots stay
   7x7 / 10x10, colours, accessible names and aria-current are untouched, and
   the breakpoint is the page's own existing 520px one, so desktop is
   unaffected. This fragment is written to 404.html alone. */
@media(max-width:520px){
  .d-carousel .d-dots{ transform:translateX(-3px); }
}"""


def die(msg):
    print("REFUSED: " + msg + " -- nothing written")
    sys.exit(2)


def sha(s):
    return hashlib.sha256(s.encode("utf-8") if isinstance(s, str) else s).hexdigest()


def strip_block(t):
    """Removes EXACTLY what the splice inserts -- one leading newline, the
    block, one trailing newline. An earlier version used \n* and greedily ate
    a newline that was already in the file, so the round trip was not
    symmetric and guard V2 refused its own output."""
    return re.sub(r"\n" + re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n",
                  "", t, flags=re.S)


def plan():
    p = {}
    for f in FOOTER_PAGES:
        p.setdefault(f, []).append(FOOTER_FIX)
    for f in ("index.html", "404.html"):
        p.setdefault(f, []).append(LEDE_FIX)
        p.setdefault(f, []).append(DOTS_FIX)
    p.setdefault("404.html", []).append(FOUR_OH_FOUR_FIX)
    p.setdefault("404.html", []).append(DOTS_404_CLEARANCE)
    for f in DISCOVERIES + ["about.html"]:
        p.setdefault(f, []).append(SAGE_ON_LIGHT_FIX)
    for f in DISCOVERIES + ["about.html", "index.html", "404.html"]:
        p.setdefault(f, []).append(REDUCED_MOTION)
    p["404.html"][-1] = REDUCED_MOTION[:-1] + HERO_404 + "\n}"
    p.setdefault("your-plot.html", []).append(MYPLOT_MOTION)
    p.setdefault("discoveries.html", []).append(DISCOVERIES_MOTION)
    return p


def build(write=True):
    # ---- S0 · protected state, asserted BEFORE anything is written -------
    d25 = (ROOT / DISC025).read_text(encoding="utf-8")
    i, j = d25.find("<main"), d25.rfind("</main>")
    if sha(d25[i:j + 7]) != DISC025_MAIN_SHA:
        die("S0 DISC-025 frozen <main> hash has already moved")
    for f, want in FROZEN.items():
        if sha((ROOT / f).read_bytes()) != want:
            die("S0 %s is not at its frozen hash" % f)
    if DISC025 in plan():
        die("S0 DISC-025 appears in the plan; it must never be a target")
    if "search.css" in plan():
        die("S0 search.css appears in the plan; Search V1 is frozen")

    results = []
    for f, parts in plan().items():
        p = ROOT / f
        if not p.exists():
            die("target %s does not exist" % f)
        base = p.read_text(encoding="utf-8")
        clean = strip_block(base)                 # idempotent: drop any old block
        block = BEGIN + "\n" + "\n".join(parts) + "\n" + END
        k = clean.rfind("</style>")
        if k < 0:
            die("%s has no </style> to append the block to" % f)
        out = clean[:k] + "\n" + block + "\n" + clean[k:]
        results.append({"file": f, "base": base, "clean": clean, "out": out,
                        "delta": len(out) - len(base), "parts": len(parts)})

    # ---- GUARDS ----------------------------------------------------------
    for r in results:
        f, out, base, clean = r["file"], r["out"], r["base"], r["clean"]

        # V1 · exactly one marked block
        if out.count(BEGIN) != 1 or out.count(END) != 1:
            die("V1 %s has %d begin / %d end markers; exactly one each is required"
                % (f, out.count(BEGIN), out.count(END)))

        # V2 · everything outside the block is byte-identical to the base
        if strip_block(out) != clean:
            die("V2 %s changed outside its own override block" % f)

        # V3 · the block is inside a <style>, not loose in the body.
        #      The counts must ignore comments and <script> bodies: 404.html
        #      mentions "<style" inside one, which left the raw tally at
        #      opens=2 closes=1 and made this test unable to fail on that page.
        #      The capability proof found that blindness; masking length-
        #      preservingly (as Job 4's L8 had to) makes every page balanced.
        def style_counts(s):
            blank = lambda m: " " * len(m.group(0))
            s = re.sub(r"<!--.*?-->", blank, s, flags=re.S)
            s = re.sub(r"<script[^>]*>.*?</script>", blank, s, flags=re.S | re.I)
            return s.count("<style"), s.count("</style>")
        before = out[:out.index(BEGIN)]
        opens, closes = style_counts(before)
        if opens <= closes:
            die("V3 %s puts the block outside any <style> element" % f)

        # V4 · no homeowner-visible text added. The block is CSS only, so any
        #      content:"" other than the dot's empty one is a red flag.
        blk = out[out.index(BEGIN):out.index(END)]
        if re.search(r'content\s*:\s*"[^"]+"', blk):
            die("V4 %s injects visible generated content" % f)

        # V5 · no brand token redefined; the overrides must stay scoped
        if re.search(r"--(brand-sage|accent|oak|ink|soft)\s*:", blk):
            die("V5 %s redefines a brand token; the fix must stay scoped" % f)

        # V6 · Search V1 markup untouched on the page
        for frag in ('<a class="pns-pill"', 'id="pnsInput"', 'src="search.js"'):
            if base.count(frag) != out.count(frag):
                die("V6 %s changed Search V1 markup (%s)" % (f, frag))

        # V7 · Job 4's contract untouched
        for frag in ('<main id="pn-main">', 'class="pn-skip"',
                     '<nav class="footer-cols" aria-label="Footer">', 'role="group"'):
            if base.count(frag) != out.count(frag):
                die("V7 %s changed the Job 4 landmark/skip/footer contract (%s)"
                    % (f, frag))

        # V8 · no font-size change anywhere in the block. Contrast may not be
        #      bought by making text bigger.
        if re.search(r"font-size\s*:", blk):
            die("V8 %s changes a font-size; contrast must be fixed with colour" % f)

    if not write:
        print("\n  --check: %d files would change, nothing written.\n" % len(results))
        for r in results:
            print("    %-44s %+6d  %d fragment(s)" % (r["file"], r["delta"], r["parts"]))
        print("\n  8 guard families passed.\n")
        return results

    for r in results:
        (ROOT / r["file"]).write_text(r["out"], encoding="utf-8")
    print("\n  wrote %d files.\n" % len(results))
    for r in results:
        print("    %-44s %+6d  %d fragment(s)" % (r["file"], r["delta"], r["parts"]))
    print("\n  8 guard families passed.\n")
    return results


def revert():
    files = sorted(plan())
    subprocess.run(["git", "checkout", "--"] + files, cwd=str(ROOT), check=True)
    print("reverted %d files" % len(files))


if __name__ == "__main__":
    if "--revert" in sys.argv:
        revert()
    else:
        build(write="--check" not in sys.argv)
