#!/usr/bin/env python3
"""
BOUNDED BUILDER · the Search entry on the 404
===============================================================================
JOB 1 · P0 JOURNEY EXITS, part 3.  Founder authorisation, 9 October 2026:
"Add Search as an obvious recovery route using the existing Search V1 entry
pattern where appropriate.  Do not redesign the otherwise-good 404."

THE HOMEOWNER PROBLEM.  404.html is a well-made recovery page — hero, four
Discovery cards, My Plot, about, contact, a full footer — and it is the one
reachable page on the site with NO route to Search.  A homeowner who mistyped a
URL or followed a dead link is exactly the homeowner who needs to search, and
Search is the only thing the page does not offer.

WHY THE 404 WAS MISSED, measured not guessed.  build-search-rail.py derives its
page list from sitemap.xml:

    pages = [p for p in re.findall(r"<loc>https://plotnua\\.ie/([^<]*)</loc>", ...)]

404.html is deliberately absent from the sitemap, so it was never in scope.
Nothing about the page itself excluded it: it carries exactly one
<a class="brand-mark"> anchor and the .brand-mark.in fade mechanism, which is
the rail builder's own majority variant.

WHY A SEPARATE BUILDER, and not an edit to build-search-rail.py.  That builder
is governed, its EXPECTED_PAGES = 21 guard exists specifically so the rail scope
cannot drift, and its R6 refuses to touch a Property Check.  Widening it would
change a frozen scope guard to add one unrelated page.  This builder instead
READS the canonical region from a page the rail builder already injected and
proves the 404's region is byte-identical to it (guard F3).  The rail builder is
not modified, not re-run, and its own pages are not touched.

WHAT IS DELIBERATELY NOT DONE
  * the 404 is not redesigned: hero, copy, Discovery carousel, My Plot link and
    footer are byte-identical afterwards (F4, F5, F6)
  * no new stub text is authored — the region is copied, not written, so the
    Search entry on the 404 cannot drift from the other 21 pages
  * sitemap.xml is NOT touched. The 404 stays out of the sitemap, which is
    correct, and that is also why re-running build-search-rail.py will neither
    strip nor duplicate this region

    python3 build-404-search.py            inject
    python3 build-404-search.py --check     guards only, write nothing
    python3 build-404-search.py --revert    restore from the recorded baseline
"""

import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATE = ROOT / "atlas-tools" / "404-search-baseline.json"

CHECK = "--check" in sys.argv
REVERT = "--revert" in sys.argv

TARGET = "404.html"
# The donor: any page the rail builder has already injected and that uses the
# majority (fading) variant. index.html is the canonical reference.
DONOR = "index.html"

BEGIN = "<!-- PLOTNUA SEARCH RAIL v1 · BEGIN · generated by " \
        "atlas-tools/build-search-rail.py — do not hand-edit -->"
END = "<!-- PLOTNUA SEARCH RAIL v1 · END -->"
MARK_RE = re.compile(r'(<a[^>]*class="brand-mark"[^>]*>.*?</a>)', re.S)

# This pins sha256(404.html WITH the Search region stripped out) -- the page
# AROUND the region this builder owns. It must be re-stamped whenever another
# authorised job edits the 404, which has now happened twice.
#
# JOB 4 (landmarks + semantics) legitimately changed 404.html through its
# own governed builder: the page gained a <main id="pn-main"> landmark,
# a skip link, role="group" in place of the false role="tablist" on the
# carousel dots, and the shared footer's h2 headings and nav landmark.
#   97c83162cdaa (Job 1) -> 6297c0f13499, re-stamped at the time.
#
# JOB 5 (shared visual accessibility layer) then legitimately added its
# marked PLOTNUA A11Y VISUAL override block to the 404's existing <style>:
# 97 insertions, 0 deletions -- footer contrast, the Discovery Library lede,
# the 24x24 carousel dot targets and the 404-mobile-only clearance. That
# re-stamp was OMITTED, so this pre-flight refused from 8ccca1e onwards and
# prove-404-search-mutations.py could not run its control for two releases.
#   6297c0f13499 (Job 4) -> 515e0897dd83, re-stamped here.
#
# Neither job touched the Search rail region itself: it has hashed
# 0b7f22d248698550 since Job 1 and still equals the donor's. No shipped 404
# or Search defect existed -- only this constant was stale.
EXPECTED_BEFORE = "515e0897dd83"


def die(msg):
    print("\nREFUSED: " + msg)
    sys.exit(1)


def sha(b):
    return hashlib.sha256(b if isinstance(b, bytes) else b.encode("utf-8")).hexdigest()


def strip_region(text):
    return re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", "",
                  text, flags=re.S)


print("\n  BOUNDED BUILDER · the Search entry on the 404\n")

baseline = json.loads(STATE.read_text(encoding="utf-8")) if STATE.exists() else {}

if REVERT:
    p = ROOT / TARGET
    restored = strip_region(p.read_text(encoding="utf-8"))
    if sha(restored) != baseline.get("before"):
        die("cannot revert cleanly: stripping the region gives %s, baseline "
            "was %s" % (sha(restored)[:12], str(baseline.get("before"))[:12]))
    p.write_text(restored, encoding="utf-8")
    print("  reverted %s to baseline\n" % TARGET)
    sys.exit(0)

# =================================================================== PRE-FLIGHT
page = (ROOT / TARGET).read_text(encoding="utf-8")
base = strip_region(page)

if sha(base)[:12] != EXPECTED_BEFORE:
    die("F0 %s baseline is %s, expected %s" % (TARGET, sha(base)[:12],
                                               EXPECTED_BEFORE))
print("  F0  %s matches its expected baseline hash  OK" % TARGET)

if len(MARK_RE.findall(base)) != 1:
    die("F1 %s has %d .brand-mark anchors; exactly one is required"
        % (TARGET, len(MARK_RE.findall(base))))
print("  F1  exactly one .brand-mark anchor — the same anchor the rail\n"
      "      builder uses on all 21 of its own pages  OK")

# The donor must already carry the rail, and the 404 must take the same variant.
donor = (ROOT / DONOR).read_text(encoding="utf-8")
if BEGIN not in donor:
    die("F2 the donor %s does not carry the Search rail" % DONOR)
REGION = donor[donor.index(BEGIN):donor.index(END) + len(END)]
if "data-pns-nofade" in REGION:
    die("F2 the donor %s uses the nofade variant; the canonical donor must be "
       "a fading page" % DONOR)
if ".brand-mark.in" not in base:
    die("F2 %s has no .brand-mark.in fade mechanism, so it would need the "
        "nofade variant and this donor is wrong" % TARGET)
print("  F2  region COPIED from %s, not authored here, and %s uses the same\n"
      "      fading variant (measured: .brand-mark.in present)  OK"
      % (DONOR, TARGET))

for f in ("search.css", "search.js"):
    if not (ROOT / f).exists():
        die("F2b the shared asset %s does not exist" % f)
print("  F2b both shared Search assets present (search.css, search.js)  OK")

# ======================================================================= BUILD
m = MARK_RE.search(base)
out = base[:m.end()] + "\n" + REGION + base[m.end():]

# ====================================================================== GUARDS
print()

# F3 — byte-identical to the canonical region on the other pages
others = {}
for p in sorted(ROOT.glob("*.html")):
    t = p.read_text(encoding="utf-8")
    if BEGIN in t and p.name != TARGET:
        r = t[t.index(BEGIN):t.index(END) + len(END)]
        others.setdefault(sha(r), []).append(p.name)
mine = sha(out[out.index(BEGIN):out.index(END) + len(END)])
if mine not in others:
    die("F3 the 404's region matches no existing page's region")
print("  F3  the 404's Search region is byte-identical to the region already\n"
      "      shipping on %d pages  %s  OK" % (len(others[mine]), mine[:16]))
for h, names in sorted(others.items(), key=lambda kv: -len(kv[1])):
    print("        %s  %2d page(s)%s" % (h[:16], len(names),
                                         "  <- the 404 joins this set"
                                         if h == mine else ""))

# F5 — the 404 is NOT redesigned: prose and every inline block identical
def prose(t):
    t = strip_region(t)
    t = re.sub(r"<script.*?</script>", " ", t, flags=re.S | re.I)
    t = re.sub(r"<style.*?</style>", " ", t, flags=re.S | re.I)
    t = re.sub(r"<!--.*?-->", " ", t, flags=re.S)
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", t)).strip()
if prose(base) != prose(out):
    die("F5 the 404's copy changed — this job does not redesign the 404")
def bodies(t, tag):
    return [x for x in re.findall(r"<%s(?:\s[^>]*)?>(.*?)</%s>" % (tag, tag),
                                  t, re.S) if x.strip()]
for tag in ("style", "script"):
    if bodies(base, tag) != bodies(strip_region(out), tag):
        die("F5 an inline <%s> body on the 404 changed" % tag)
print("  F5  404 hero, copy, Discovery carousel and footer byte-identical;\n"
      "      no inline <style> or <script> body changed  OK")

# F6 — every pre-existing recovery route on the 404 survives
HREF_RE = re.compile(r'<a\b[^>]*href="([^"]+)"[^>]*>(.*?)</a>', re.S)
missing = [x for x in HREF_RE.findall(base) if x not in HREF_RE.findall(out)]
if missing:
    die("F6 a pre-existing 404 recovery route was lost: %r" % missing[:3])
print("  F6  all %d pre-existing anchors on the 404 still present  OK"
      % len(HREF_RE.findall(base)))

# F7 — sitemap untouched, and the 404 still absent from it
sm = (ROOT / "sitemap.xml").read_text(encoding="utf-8")
if "404" in sm:
    die("F7 404.html appears in sitemap.xml; it must not be indexed")
print("  F7  sitemap.xml untouched and the 404 is still not listed  OK")

# F8 — the 404 keeps its noindex posture
if not re.search(r'name="robots"[^>]*noindex', base):
    die("F8 %s has no noindex robots directive to preserve" % TARGET)
if re.search(r'name="robots"[^>]*noindex', base).group(0) not in out:
    die("F8 the noindex directive changed")
print("  F8  the 404's noindex directive preserved  OK")

# F4 — the catch-all. Every byte outside the injection point unchanged.
#      Deliberately AFTER F5/F6/F8: it would otherwise claim every failure
#      those guards describe better. The mutation proof caught exactly that
#      misattribution three times, and this ordering is the fix.
if strip_region(out) != base:
    die("F4 %s changed outside the injection point" % TARGET)
print("  F4  every byte outside the injection point unchanged  OK")

# F9 — idempotence
if out.count(BEGIN) != 1 or out.count(END) != 1:
    die("F9 %s does not carry exactly one region" % TARGET)
again = strip_region(out)
m2 = MARK_RE.search(again)
if again[:m2.end()] + "\n" + REGION + again[m2.end():] != out:
    die("F9 not idempotent under re-injection")
print("  F9  exactly one region, and re-injection is idempotent  OK")

# F10 — the Search entry works without JavaScript
if 'href="search.html"' not in REGION:
    die("F10 the region has no real href to search.html")
print("  F10 the pill is a real <a href=\"search.html\">, so Search is\n"
      "      reachable from the 404 with JavaScript disabled  OK")

print("\n  11 guards passed.")

if CHECK:
    print("  --check: nothing written.\n")
    sys.exit(0)

(ROOT / TARGET).write_text(out, encoding="utf-8")
STATE.write_text(json.dumps({"before": sha(base), "after": sha(out),
                             "region": mine, "donor": DONOR},
                            indent=2, sort_keys=True), encoding="utf-8")
print("  WROTE %s   %s -> %s\n" % (TARGET, sha(base)[:12], sha(out)[:12]))
